spring:
  servlet:
    multipart:
      max-file-size: 10MB

  kafka:
    consumer:
      group-id: file-service

minio:
  url: ${MINIO_URL:http://minio:9000}
  access-key: minio
  secret-key: minio123
  buckets:
    default: default
    user-files: user-files
  formats:
    transport-photos: transport-photos/%d/%s.jpeg
    reports: reports/%d/%s.pdf
  date-format: yyyy-MM-dd_HH-mm-ss

server:
  port: 8084
