INSERT INTO roles(name) VALUES ('ADMIN');
INSERT INTO roles(name) VALUES ('MISSION_COMMANDER');
INSERT INTO roles(name) VALUES ('LOGISTICS_OFFICER');
INSERT INTO roles(name) VALUES ('MAINTENANCE_ENGINEER');
